export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const CONTACTS_IS_LOADING = "CONTACTS_IS_LOADING";
export const CONTACTS_HAS_ERRORED = "CONTACTS_HAS_ERRORED";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";