export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const CONTACTS_IS_PROCESSING = "CONTACTS_IS_PROCESSING";
export const CONTACTS_HAS_ERRORED = "CONTACTS_HAS_ERRORED";

export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const SORT_CONTACT_DATA = "SORT_CONTACT_DATA";
